default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"

  lane :firebase_distribution do

    # نرجع من android إلى root مشروع Flutter
    sh "cd .. && flutter clean"
    sh "cd .. && flutter pub get"

    # Build Production APK
    sh "cd .. && flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"

    # Upload APK to Firebase App Distribution
    firebase_app_distribution(
      app: "1:395686173932:android:76eb1ec4d79dceb2e199c9",
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "khalafyd@gmail.com",
      release_notes: "Production release"
    )
  end
end